name: Test
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20",1.21,1.22]
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
      ssdb:
        image: tsl0922/ssdb
        env:
          SSDB_PORT: 8888
        ports:
          - "8888:8888"
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orm_test
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run ORM tests on postgres
        env:
          GOPATH: /home/runner/go
          ORM_DRIVER: postgres
          ORM_SOURCE: host=localhost port=${{ job.services.postgres.ports[5432] }} user=postgres password=postgres dbname=orm_test sslmode=disable
        run: |
          go test -coverprofile=coverage_postgres.txt -covermode=atomic $(go list ./... | grep client/orm)

      - name: Run tests on mysql
        env:
          GOPATH: /home/runner/go
          ORM_DRIVER: mysql
          ORM_SOURCE: root:root@/orm_test?charset=utf8
        run: |
          sudo systemctl start mysql
          mysql -u root -proot -e 'create database orm_test;'
          go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload codecov
        env:
          CODECOV_TOKEN: 4f4bc484-32a8-43b7-9f48-20966bd48ceb
        run: bash <(curl -s https://codecov.io/bash)
